package com.example.autoelite_android.util

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.unit.LayoutDirection

data class AppStrings(
    // General
    val cancel: String,
    val close: String,
    val save: String,
    val back: String,
    val refresh: String,
    val search: String,
    val clearSearch: String,
    val all: String,
    val send: String,
    val apply: String,
    val accept: String,
    val reject: String,
    val delete: String,
    val fillAllFields: String,
    val noConnection: String,
    val layoutDirection: LayoutDirection,
    val undoWarning: String,

    // Bottom Nav
    val navHome: String,
    val navCitas: String,
    val navVehiculos: String,
    val navReparaciones: String,
    val navPerfil: String,

    // Auth
    val appSubtitle: String,
    val emailField: String,
    val passwordField: String,
    val showPassword: String,
    val hidePassword: String,
    val loginButton: String,
    val noAccount: String,
    val registerLink: String,
    val registerTitle: String,
    val registerSubtitle: String,
    val firstNameField: String,
    val lastNameField: String,
    val confirmPasswordField: String,
    val passwordsNotMatch: String,
    val minPasswordChars: String,
    val createAccountButton: String,
    val alreadyHaveAccount: String,
    val signInLink: String,

    // Home
    val homeGreeting: (String) -> String,
    val homeSubtitle: String,
    val quickAccess: String,
    val quickCitas: String,
    val quickCitasSub: String,
    val quickReparaciones: String,
    val quickReparacionesSub: String,
    val quickVehiculos: String,
    val quickVehiculosSub: String,
    val quickCrm: String,
    val quickCrmSub: String,
    val quickFacturas: String,
    val quickFacturasSub: String,
    val quickHistorial: String,
    val quickHistorialSub: String,
    val nextCita: String,
    val serviceLabel: String,
    val noCitasScheduled: String,
    val bookNextCita: String,
    val notificationsLabel: String,

    // Citas
    val myCitas: String,
    val searchCitasHint: String,
    val noCitas: String,
    val noCitasFilter: String,
    val bookCita: String,
    val newCita: String,
    val cancelCitaTitle: String,
    val cancelCitaQuestion: (String, String) -> String,
    val vehicleField: String,
    val dateField: String,
    val availableSlots: String,
    val noSlotsAvailable: String,
    val selectDateFirst: String,
    val serviceTypeField: String,
    val workshopConfirmDesc: String,
    val requestButton: String,
    val citaCountLabel: (Int) -> String,
    val filterAll: String,
    val filterPending: String,
    val filterConfirmed: String,
    val filterCancelled: String,
    val noVehiclesForCita: String,
    val citaStatusPending: String,
    val citaStatusConfirmed: String,
    val citaStatusCancelled: String,

    // Vehiculos
    val myVehiculos: String,
    val noVehiculos: String,
    val addVehiculo: String,
    val updateKmButton: String,
    val deleteVehiculoButton: String,
    val deleteVehiculoTitle: String,
    val deleteVehiculoText: (String, String, String) -> String,
    val brandField: String,
    val modelField: String,
    val yearField: String,
    val plateField: String,
    val mileageField: String,
    val currentMileageLabel: (Int) -> String,
    val newMileageField: String,
    val vehiculoAddedMsg: String,
    val vehiculoDeletedMsg: String,
    val kmUpdatedMsg: String,
    val invalidNumberError: String,
    val negativeKmError: String,
    val kmCannotDecreaseError: (Int) -> String,
    val cannotDeleteVehiculo: String,
    val updateMileageTitle: String,
    val kmSuffix: String,

    // Reparaciones
    val myReparaciones: String,
    val searchReparacionesHint: String,
    val noReparaciones: String,
    val noReparacionesFilter: String,
    val mechanicLabel: String,
    val costLabel: String,
    val vehicleStatusLabel: String,
    val rejectedRepairLabel: String,
    val repairPresentedDesc: String,
    val rateRepairButton: String,
    val ratingSentMsg: String,
    val acceptRepairTitle: String,
    val rejectRepairTitle: String,
    val acceptRepairText: (String, String, String) -> String,
    val rejectRepairText: (String, String) -> String,
    val howWasExperience: String,
    val commentOptional: String,
    val stepPresented: String,
    val stepInProgress: String,
    val stepFinished: String,
    val stepConfirmed: String,
    val ratingVeryBad: String,
    val ratingBad: String,
    val ratingNormal: String,
    val ratingGood: String,
    val ratingExcellent: String,
    val reparacionCountLabel: (Int) -> String,
    val filterPresented: String,
    val filterInProgress: String,
    val filterFinished: String,
    val filterConfirmedRep: String,
    val filterRejected: String,
    val ratingRepair: String,

    // Facturacion
    val myFacturas: String,
    val searchFacturasHint: String,
    val noFacturas: String,
    val noFacturasFilter: String,
    val paidLabel: String,
    val unpaidLabel: String,
    val paymentMethodLabel: String,
    val sharePdfButton: String,
    val payButton: String,
    val generatingLabel: String,
    val payingLabel: String,
    val pdfErrorMsg: String,
    val facturaCountLabel: (Int) -> String,
    val filterAllFacturas: String,
    val filterPaidFacturas: String,
    val filterUnpaidFacturas: String,

    // CRM
    val myPointsTitle: String,
    val ptsLabel: String,
    val levelLabel: String,
    val goldLevel: String,
    val silverLevel: String,
    val bronzeLevel: String,
    val maxLevelReached: String,
    val pointsToGold: (Int) -> String,
    val pointsToSilver: (Int) -> String,
    val availableRewards: String,
    val pointsInfoText: String,
    val redeemButton: String,
    val redeemingLabel: String,
    val redeemRewardTitle: String,
    val confirmRedeemButton: String,
    val yourCurrentPoints: String,
    val rewardCostLabel: String,
    val remainingPointsLabel: String,
    val redeemEmailInfo: String,
    val reward1Title: String,
    val reward1Desc: String,
    val reward2Title: String,
    val reward2Desc: String,
    val reward3Title: String,
    val reward3Desc: String,
    val reward4Title: String,
    val reward4Desc: String,

    // Notificaciones
    val notificationsTitle: String,
    val markAllRead: String,
    val noNotifications: String,
    val noNotificationsDesc: String,

    // Historial
    val historialTitle: String,
    val noHistory: String,
    val noHistoryDesc: String,
    val citasHistLabel: String,
    val reparacionesHistLabel: String,
    val facturasHistLabel: String,
    val appointmentServiceLabel: String,
    val mechanicHistLabel: (String) -> String,
    val paidHistLabel: String,
    val unpaidHistLabel: String,
    val monthNames: List<String>,
    val statusReadable: (String) -> String,

    // Perfil
    val myProfile: String,
    val pointsAccumulated: (Int) -> String,
    val appearanceSection: String,
    val darkModeLabel: String,
    val languageLabel: String,
    val languageDialogTitle: String,
    val languageDialogDesc: String,
    val accountSection: String,
    val editPersonalDataLabel: String,
    val changePasswordLabel: String,
    val notifSectionLabel: String,
    val supportSection: String,
    val workshopLocationLabel: String,
    val contactWorkshopLabel: String,
    val aboutAutoEliteLabel: String,
    val logoutButton: String,
    val logoutTitle: String,
    val logoutDesc: String,
    val exitButton: String,
    val editDataTitle: String,
    val nameField: String,
    val surnamesField: String,
    val phoneField: String,
    val currentPasswordFieldLabel: String,
    val newPasswordFieldLabel: String,
    val confirmNewPasswordField: String,
    val changePasswordButton: String,
    val citasNotifLabel: String,
    val repairsNotifLabel: String,
    val promoNotifLabel: String,
    val savedAutomatically: String,
    val openInMaps: String,
    val callButton: (String) -> String,
    val emailButton: (String) -> String,
    val whatsappButton: String,
    val versionLabel: String,
    val developerLabel: String,
    val platformLabel: String,
    val backendLabel: String,
    val aboutDescText: String,
    val spanishLang: String,
    val englishLang: String,
    val arabicLang: String,
    val workshopNameLabel: String,
    val workshopAddressLabel: String,
    val workshopSchedule: String,
    val changePasswordTitle: String,
    val errorGeneric: String,
    val goBack: String,
)

// ESPAÑOL
val StringsEs = AppStrings(
    cancel = "Cancelar",
    close = "Cerrar",
    save = "Guardar",
    back = "Volver",
    refresh = "Actualizar",
    search = "Buscar",
    clearSearch = "Limpiar",
    all = "Todas",
    send = "Enviar",
    apply = "Aplicar",
    accept = "Aceptar",
    reject = "Rechazar",
    delete = "Eliminar",
    fillAllFields = "Rellena todos los campos",
    noConnection = "Sin conexión con el servidor",
    layoutDirection = LayoutDirection.Ltr,
    undoWarning = "Esta acción no se puede deshacer.",
    goBack = "Volver",

    navHome = "Inicio",
    navCitas = "Citas",
    navVehiculos = "Vehículos",
    navReparaciones = "Reparaciones",
    navPerfil = "Perfil",

    appSubtitle = "Gestión de talleres",
    emailField = "Correo electrónico",
    passwordField = "Contraseña",
    showPassword = "Mostrar",
    hidePassword = "Ocultar",
    loginButton = "Iniciar sesión",
    noAccount = "¿No tienes cuenta?",
    registerLink = "Regístrate",
    registerTitle = "Únete a AutoElite",
    registerSubtitle = "Crea tu cuenta para gestionar tus citas y vehículos",
    firstNameField = "Nombre",
    lastNameField = "Apellidos",
    confirmPasswordField = "Confirmar contraseña",
    passwordsNotMatch = "Las contraseñas no coinciden",
    minPasswordChars = "Mínimo 6 caracteres",
    createAccountButton = "Crear cuenta",
    alreadyHaveAccount = "¿Ya tienes cuenta?",
    signInLink = "Inicia sesión",

    homeGreeting = { "Hola, $it" },
    homeSubtitle = "Bienvenido a tu taller de confianza",
    quickAccess = "Acceso rápido",
    quickCitas = "Pedir cita",
    quickCitasSub = "Agenda tu visita",
    quickReparaciones = "Reparaciones",
    quickReparacionesSub = "Seguimiento en vivo",
    quickVehiculos = "Vehículos",
    quickVehiculosSub = "Gestiona tu flota",
    quickCrm = "Puntos CRM",
    quickCrmSub = "Canjea recompensas",
    quickFacturas = "Facturas",
    quickFacturasSub = "Paga online",
    quickHistorial = "Historial",
    quickHistorialSub = "Tu actividad",
    nextCita = "Próxima cita",
    serviceLabel = "Servicio",
    noCitasScheduled = "Sin citas programadas",
    bookNextCita = "Pide tu próxima cita ahora",
    notificationsLabel = "Notificaciones",

    myCitas = "Mis citas",
    searchCitasHint = "Buscar por vehículo, tipo, fecha…",
    noCitas = "No tienes citas aún",
    noCitasFilter = "No se encontraron citas con esos filtros",
    bookCita = "Pedir una cita",
    newCita = "Nueva cita",
    cancelCitaTitle = "Cancelar cita",
    cancelCitaQuestion = { date, time -> "¿Estás seguro de que quieres cancelar la cita del $date a las $time?" },
    vehicleField = "Vehículo",
    dateField = "Fecha",
    availableSlots = "Horarios disponibles:",
    noSlotsAvailable = "No hay horas disponibles para este día.",
    selectDateFirst = "Selecciona una fecha para ver los horarios disponibles",
    serviceTypeField = "Tipo de servicio",
    workshopConfirmDesc = "El taller confirmará la disponibilidad",
    requestButton = "Solicitar",
    citaCountLabel = { n -> "$n cita${if (n != 1) "s" else ""}" },
    filterAll = "Todas",
    filterPending = "Pendientes",
    filterConfirmed = "Confirmadas",
    filterCancelled = "Canceladas",
    noVehiclesForCita = "No tienes vehículos registrados",
    citaStatusPending = "PENDIENTE",
    citaStatusConfirmed = "CONFIRMADA",
    citaStatusCancelled = "CANCELADA",

    myVehiculos = "Mis vehículos",
    noVehiculos = "No tienes vehículos registrados",
    addVehiculo = "Añadir vehículo",
    updateKmButton = "Actualizar km",
    deleteVehiculoButton = "Eliminar",
    deleteVehiculoTitle = "Eliminar vehículo",
    deleteVehiculoText = { m, mo, p -> "¿Estás seguro de que quieres eliminar el $m $mo ($p)?\n\nEsta acción no se puede deshacer." },
    brandField = "Marca",
    modelField = "Modelo",
    yearField = "Año",
    plateField = "Matrícula",
    mileageField = "Kilometraje",
    currentMileageLabel = { km -> "Kilometraje actual: $km km" },
    newMileageField = "Nuevo kilometraje",
    vehiculoAddedMsg = "Vehículo añadido",
    vehiculoDeletedMsg = "Vehículo eliminado",
    kmUpdatedMsg = "Kilometraje actualizado",
    invalidNumberError = "Introduce un número válido",
    negativeKmError = "El kilometraje no puede ser negativo",
    kmCannotDecreaseError = { km -> "El kilometraje no puede ser menor al actual ($km km)" },
    cannotDeleteVehiculo = "No se puede eliminar: tiene citas o reparaciones asociadas",
    updateMileageTitle = "Actualizar kilometraje",
    kmSuffix = "km",

    myReparaciones = "Mis reparaciones",
    searchReparacionesHint = "Buscar por vehículo, matrícula, mecánico…",
    noReparaciones = "Sin reparaciones activas",
    noReparacionesFilter = "No se encontraron reparaciones",
    mechanicLabel = "Mecánico:",
    costLabel = "Coste:",
    vehicleStatusLabel = "Estado del vehículo",
    rejectedRepairLabel = "Reparación rechazada",
    repairPresentedDesc = "El taller te ha presentado esta reparación. ¿Deseas aceptarla?",
    rateRepairButton = "Valorar reparación",
    ratingSentMsg = "Valoración enviada. ¡Gracias!",
    acceptRepairTitle = "Aceptar reparación",
    rejectRepairTitle = "Rechazar reparación",
    acceptRepairText = { v, p, c -> "¿Aceptas la reparación de $v · $p por $c €?\n\nEl taller comenzará a trabajar en tu vehículo." },
    rejectRepairText = { v, p -> "¿Estás seguro de que quieres rechazar la reparación de $v · $p?\n\nEsta acción no se puede deshacer." },
    howWasExperience = "¿Cómo fue tu experiencia?",
    commentOptional = "Comentario (opcional)",
    stepPresented = "Presentada",
    stepInProgress = "En proceso",
    stepFinished = "Terminada",
    stepConfirmed = "Confirmada",
    ratingVeryBad = "Muy malo",
    ratingBad = "Malo",
    ratingNormal = "Normal",
    ratingGood = "Bueno",
    ratingExcellent = "Excelente",
    reparacionCountLabel = { n -> "$n reparación${if (n != 1) "es" else ""}" },
    filterPresented = "Presentadas",
    filterInProgress = "En proceso",
    filterFinished = "Terminadas",
    filterConfirmedRep = "Confirmadas",
    filterRejected = "Rechazadas",
    ratingRepair = "Valorar reparación",

    myFacturas = "Mis facturas",
    searchFacturasHint = "Buscar por nº factura, fecha, importe…",
    noFacturas = "No tienes facturas aún",
    noFacturasFilter = "No se encontraron facturas",
    paidLabel = "✓ Pagada",
    unpaidLabel = "Pendiente",
    paymentMethodLabel = "Método:",
    sharePdfButton = "Compartir PDF",
    payButton = "Pagar",
    generatingLabel = "Generando…",
    payingLabel = "Pagando…",
    pdfErrorMsg = "Error al generar el PDF",
    facturaCountLabel = { n -> "$n factura${if (n != 1) "s" else ""}" },
    filterAllFacturas = "Todas",
    filterPaidFacturas = "Pagadas",
    filterUnpaidFacturas = "Pendientes",

    myPointsTitle = "Mis puntos",
    ptsLabel = "pts",
    levelLabel = "Nivel:",
    goldLevel = "Gold 🥇",
    silverLevel = "Silver 🥈",
    bronzeLevel = "Bronze 🥉",
    maxLevelReached = "Has alcanzado el nivel máximo",
    pointsToGold = { pts -> "Gold — faltan $pts puntos" },
    pointsToSilver = { pts -> "Silver — faltan $pts puntos" },
    availableRewards = "Recompensas disponibles",
    pointsInfoText = "Acumulas puntos con cada reparación. 1 € gastado = 1 punto acumulado.",
    redeemButton = "Canjear",
    redeemingLabel = "Canjeando…",
    redeemRewardTitle = "Canjear recompensa",
    confirmRedeemButton = "Confirmar canjeo",
    yourCurrentPoints = "Tus puntos actuales:",
    rewardCostLabel = "Coste de la recompensa:",
    remainingPointsLabel = "Puntos restantes:",
    redeemEmailInfo = "Recibirás un código por email para usar en tu próxima visita.",
    reward1Title = "10% de descuento",
    reward1Desc = "En tu próxima reparación",
    reward2Title = "Revisión gratuita",
    reward2Desc = "Revisión completa sin coste",
    reward3Title = "Cambio de aceite",
    reward3Desc = "Mano de obra incluida",
    reward4Title = "25% de descuento",
    reward4Desc = "En cualquier servicio",

    notificationsTitle = "Notificaciones",
    markAllRead = "Marcar todas leídas",
    noNotifications = "No tienes notificaciones",
    noNotificationsDesc = "Aquí aparecerán las actualizaciones de tus citas,\nreparaciones y facturas",

    historialTitle = "Historial",
    noHistory = "Aún no hay actividad",
    noHistoryDesc = "Tus citas, reparaciones y pagos aparecerán aquí",
    citasHistLabel = "Citas",
    reparacionesHistLabel = "Reparaciones",
    facturasHistLabel = "Facturas",
    appointmentServiceLabel = "Cita de servicio",
    mechanicHistLabel = { mec -> "Mecánico: $mec" },
    paidHistLabel = "Pagada",
    unpaidHistLabel = "Pendiente de pago",
    monthNames = listOf("Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"),
    statusReadable = { e -> when(e) { "PENDIENTE"->"Pendiente"; "CONFIRMADA"->"Confirmada"; "CANCELADA"->"Cancelada"; "EN_PROCESO"->"En proceso"; "TERMINADA"->"Terminada"; "PRESENTADA"->"Presentada"; else->e.lowercase().replaceFirstChar{it.uppercase()} } },

    myProfile = "Mi perfil",
    pointsAccumulated = { pts -> "$pts puntos acumulados" },
    appearanceSection = "Apariencia",
    darkModeLabel = "Modo oscuro",
    languageLabel = "Idioma",
    languageDialogTitle = "Idioma de la app",
    languageDialogDesc = "La app se adaptará al idioma seleccionado automáticamente.",
    accountSection = "Cuenta",
    editPersonalDataLabel = "Editar datos personales",
    changePasswordLabel = "Cambiar contraseña",
    notifSectionLabel = "Notificaciones",
    supportSection = "Soporte",
    workshopLocationLabel = "Localización del taller",
    contactWorkshopLabel = "Contactar con el taller",
    aboutAutoEliteLabel = "Acerca de AutoElite",
    logoutButton = "Cerrar sesión",
    logoutTitle = "¿Cerrar sesión?",
    logoutDesc = "Se cerrará tu sesión en este dispositivo.",
    exitButton = "Salir",
    editDataTitle = "Editar datos",
    nameField = "Nombre",
    surnamesField = "Apellidos",
    phoneField = "Teléfono",
    currentPasswordFieldLabel = "Contraseña actual",
    newPasswordFieldLabel = "Nueva contraseña",
    confirmNewPasswordField = "Confirmar nueva",
    changePasswordButton = "Cambiar",
    citasNotifLabel = "Citas y recordatorios",
    repairsNotifLabel = "Estado de reparaciones",
    promoNotifLabel = "Promociones y ofertas",
    savedAutomatically = "Se guardan automáticamente",
    openInMaps = "Abrir en Maps",
    callButton = { tel -> "Llamar: $tel" },
    emailButton = { mail -> "Email: $mail" },
    whatsappButton = "WhatsApp",
    versionLabel = "Versión",
    developerLabel = "Desarrollador",
    platformLabel = "Plataforma",
    backendLabel = "Backend",
    aboutDescText = "Aplicación desarrollada como TFG para gestión centralizada de citas, vehículos, reparaciones y facturación.",
    spanishLang = "Español",
    englishLang = "English",
    arabicLang = "العربية",
    workshopNameLabel = "AutoElite Taller",
    workshopAddressLabel = "Avenida de las Vascongadas, Getafe",
    workshopSchedule = "Lun-Vie: 8:00–18:00\nSáb: 9:00–14:00",
    changePasswordTitle = "Cambiar contraseña",
    errorGeneric = "Ha ocurrido un error",
)

// ENGLISH
val StringsEn = AppStrings(
    cancel = "Cancel",
    close = "Close",
    save = "Save",
    back = "Back",
    refresh = "Refresh",
    search = "Search",
    clearSearch = "Clear",
    all = "All",
    send = "Send",
    apply = "Apply",
    accept = "Accept",
    reject = "Reject",
    delete = "Delete",
    fillAllFields = "Fill in all fields",
    noConnection = "No connection to server",
    layoutDirection = LayoutDirection.Ltr,
    undoWarning = "This action cannot be undone.",
    goBack = "Back",

    navHome = "Home",
    navCitas = "Appointments",
    navVehiculos = "Vehicles",
    navReparaciones = "Repairs",
    navPerfil = "Profile",

    appSubtitle = "Workshop management",
    emailField = "Email address",
    passwordField = "Password",
    showPassword = "Show",
    hidePassword = "Hide",
    loginButton = "Sign in",
    noAccount = "Don't have an account?",
    registerLink = "Sign up",
    registerTitle = "Join AutoElite",
    registerSubtitle = "Create your account to manage your appointments and vehicles",
    firstNameField = "First name",
    lastNameField = "Last name",
    confirmPasswordField = "Confirm password",
    passwordsNotMatch = "Passwords do not match",
    minPasswordChars = "Minimum 6 characters",
    createAccountButton = "Create account",
    alreadyHaveAccount = "Already have an account?",
    signInLink = "Sign in",

    homeGreeting = { "Hello, $it" },
    homeSubtitle = "Welcome to your trusted workshop",
    quickAccess = "Quick access",
    quickCitas = "Book appointment",
    quickCitasSub = "Schedule your visit",
    quickReparaciones = "Repairs",
    quickReparacionesSub = "Live tracking",
    quickVehiculos = "Vehicles",
    quickVehiculosSub = "Manage your fleet",
    quickCrm = "CRM Points",
    quickCrmSub = "Redeem rewards",
    quickFacturas = "Invoices",
    quickFacturasSub = "Pay online",
    quickHistorial = "History",
    quickHistorialSub = "Your activity",
    nextCita = "Next appointment",
    serviceLabel = "Service",
    noCitasScheduled = "No appointments scheduled",
    bookNextCita = "Book your next appointment now",
    notificationsLabel = "Notifications",

    myCitas = "My appointments",
    searchCitasHint = "Search by vehicle, type, date…",
    noCitas = "No appointments yet",
    noCitasFilter = "No appointments found with those filters",
    bookCita = "Book an appointment",
    newCita = "New appointment",
    cancelCitaTitle = "Cancel appointment",
    cancelCitaQuestion = { date, time -> "Are you sure you want to cancel the appointment on $date at $time?" },
    vehicleField = "Vehicle",
    dateField = "Date",
    availableSlots = "Available time slots:",
    noSlotsAvailable = "No time slots available for this day.",
    selectDateFirst = "Select a date to see available time slots",
    serviceTypeField = "Service type",
    workshopConfirmDesc = "The workshop will confirm availability",
    requestButton = "Request",
    citaCountLabel = { n -> "$n appointment${if (n != 1) "s" else ""}" },
    filterAll = "All",
    filterPending = "Pending",
    filterConfirmed = "Confirmed",
    filterCancelled = "Cancelled",
    noVehiclesForCita = "You have no registered vehicles",
    citaStatusPending = "PENDIENTE",
    citaStatusConfirmed = "CONFIRMADA",
    citaStatusCancelled = "CANCELADA",

    myVehiculos = "My vehicles",
    noVehiculos = "No registered vehicles",
    addVehiculo = "Add vehicle",
    updateKmButton = "Update mileage",
    deleteVehiculoButton = "Delete",
    deleteVehiculoTitle = "Delete vehicle",
    deleteVehiculoText = { m, mo, p -> "Are you sure you want to delete the $m $mo ($p)?\n\nThis action cannot be undone." },
    brandField = "Brand",
    modelField = "Model",
    yearField = "Year",
    plateField = "License plate",
    mileageField = "Mileage",
    currentMileageLabel = { km -> "Current mileage: $km km" },
    newMileageField = "New mileage",
    vehiculoAddedMsg = "Vehicle added",
    vehiculoDeletedMsg = "Vehicle deleted",
    kmUpdatedMsg = "Mileage updated",
    invalidNumberError = "Enter a valid number",
    negativeKmError = "Mileage cannot be negative",
    kmCannotDecreaseError = { km -> "Mileage cannot be less than current ($km km)" },
    cannotDeleteVehiculo = "Cannot delete: has associated appointments or repairs",
    updateMileageTitle = "Update mileage",
    kmSuffix = "km",

    myReparaciones = "My repairs",
    searchReparacionesHint = "Search by vehicle, plate, mechanic…",
    noReparaciones = "No active repairs",
    noReparacionesFilter = "No repairs found",
    mechanicLabel = "Mechanic:",
    costLabel = "Cost:",
    vehicleStatusLabel = "Vehicle status",
    rejectedRepairLabel = "Repair rejected",
    repairPresentedDesc = "The workshop has presented this repair. Do you want to accept it?",
    rateRepairButton = "Rate repair",
    ratingSentMsg = "Rating sent. Thank you!",
    acceptRepairTitle = "Accept repair",
    rejectRepairTitle = "Reject repair",
    acceptRepairText = { v, p, c -> "Do you accept the repair of $v · $p for $c €?\n\nThe workshop will start working on your vehicle." },
    rejectRepairText = { v, p -> "Are you sure you want to reject the repair of $v · $p?\n\nThis action cannot be undone." },
    howWasExperience = "How was your experience?",
    commentOptional = "Comment (optional)",
    stepPresented = "Presented",
    stepInProgress = "In progress",
    stepFinished = "Finished",
    stepConfirmed = "Confirmed",
    ratingVeryBad = "Very bad",
    ratingBad = "Bad",
    ratingNormal = "Normal",
    ratingGood = "Good",
    ratingExcellent = "Excellent",
    reparacionCountLabel = { n -> "$n repair${if (n != 1) "s" else ""}" },
    filterPresented = "Presented",
    filterInProgress = "In progress",
    filterFinished = "Finished",
    filterConfirmedRep = "Confirmed",
    filterRejected = "Rejected",
    ratingRepair = "Rate repair",

    myFacturas = "My invoices",
    searchFacturasHint = "Search by invoice number, date, amount…",
    noFacturas = "No invoices yet",
    noFacturasFilter = "No invoices found",
    paidLabel = "✓ Paid",
    unpaidLabel = "Unpaid",
    paymentMethodLabel = "Method:",
    sharePdfButton = "Share PDF",
    payButton = "Pay",
    generatingLabel = "Generating…",
    payingLabel = "Paying…",
    pdfErrorMsg = "Error generating PDF",
    facturaCountLabel = { n -> "$n invoice${if (n != 1) "s" else ""}" },
    filterAllFacturas = "All",
    filterPaidFacturas = "Paid",
    filterUnpaidFacturas = "Unpaid",

    myPointsTitle = "My points",
    ptsLabel = "pts",
    levelLabel = "Level:",
    goldLevel = "Gold 🥇",
    silverLevel = "Silver 🥈",
    bronzeLevel = "Bronze 🥉",
    maxLevelReached = "You have reached the maximum level",
    pointsToGold = { pts -> "Gold — $pts points to go" },
    pointsToSilver = { pts -> "Silver — $pts points to go" },
    availableRewards = "Available rewards",
    pointsInfoText = "Earn points with every repair. €1 spent = 1 point.",
    redeemButton = "Redeem",
    redeemingLabel = "Redeeming…",
    redeemRewardTitle = "Redeem reward",
    confirmRedeemButton = "Confirm redemption",
    yourCurrentPoints = "Your current points:",
    rewardCostLabel = "Reward cost:",
    remainingPointsLabel = "Remaining points:",
    redeemEmailInfo = "You will receive a code by email to use on your next visit.",
    reward1Title = "10% discount",
    reward1Desc = "On your next repair",
    reward2Title = "Free inspection",
    reward2Desc = "Full inspection at no cost",
    reward3Title = "Oil change",
    reward3Desc = "Labour included",
    reward4Title = "25% discount",
    reward4Desc = "On any service",

    notificationsTitle = "Notifications",
    markAllRead = "Mark all as read",
    noNotifications = "No notifications",
    noNotificationsDesc = "Updates about your appointments,\nrepairs and invoices will appear here",

    historialTitle = "History",
    noHistory = "No activity yet",
    noHistoryDesc = "Your appointments, repairs and payments will appear here",
    citasHistLabel = "Appointments",
    reparacionesHistLabel = "Repairs",
    facturasHistLabel = "Invoices",
    appointmentServiceLabel = "Service appointment",
    mechanicHistLabel = { mec -> "Mechanic: $mec" },
    paidHistLabel = "Paid",
    unpaidHistLabel = "Pending payment",
    monthNames = listOf("January","February","March","April","May","June","July","August","September","October","November","December"),
    statusReadable = { e -> when(e) { "PENDIENTE"->"Pending"; "CONFIRMADA"->"Confirmed"; "CANCELADA"->"Cancelled"; "EN_PROCESO"->"In progress"; "TERMINADA"->"Finished"; "PRESENTADA"->"Presented"; else->e.lowercase().replaceFirstChar{it.uppercase()} } },

    myProfile = "My profile",
    pointsAccumulated = { pts -> "$pts points accumulated" },
    appearanceSection = "Appearance",
    darkModeLabel = "Dark mode",
    languageLabel = "Language",
    languageDialogTitle = "App language",
    languageDialogDesc = "The app will adapt to the selected language automatically.",
    accountSection = "Account",
    editPersonalDataLabel = "Edit personal data",
    changePasswordLabel = "Change password",
    notifSectionLabel = "Notifications",
    supportSection = "Support",
    workshopLocationLabel = "Workshop location",
    contactWorkshopLabel = "Contact workshop",
    aboutAutoEliteLabel = "About AutoElite",
    logoutButton = "Sign out",
    logoutTitle = "Sign out?",
    logoutDesc = "Your session will be closed on this device.",
    exitButton = "Sign out",
    editDataTitle = "Edit data",
    nameField = "Name",
    surnamesField = "Last name",
    phoneField = "Phone",
    currentPasswordFieldLabel = "Current password",
    newPasswordFieldLabel = "New password",
    confirmNewPasswordField = "Confirm new",
    changePasswordButton = "Change",
    citasNotifLabel = "Appointments & reminders",
    repairsNotifLabel = "Repair status",
    promoNotifLabel = "Promotions & offers",
    savedAutomatically = "Saved automatically",
    openInMaps = "Open in Maps",
    callButton = { tel -> "Call: $tel" },
    emailButton = { mail -> "Email: $mail" },
    whatsappButton = "WhatsApp",
    versionLabel = "Version",
    developerLabel = "Developer",
    platformLabel = "Platform",
    backendLabel = "Backend",
    aboutDescText = "Application developed as a final degree project for centralized management of appointments, vehicles, repairs and invoicing.",
    spanishLang = "Español",
    englishLang = "English",
    arabicLang = "العربية",
    workshopNameLabel = "AutoElite Workshop",
    workshopAddressLabel = "Example Street 42, 28001 Madrid",
    workshopSchedule = "Mon-Fri: 8:00–18:00\nSat: 9:00–14:00",
    changePasswordTitle = "Change password",
    errorGeneric = "An error occurred",
)

// ARABIC  (العربية)
val StringsAr = AppStrings(
    cancel = "إلغاء",
    close = "إغلاق",
    save = "حفظ",
    back = "رجوع",
    refresh = "تحديث",
    search = "بحث",
    clearSearch = "مسح",
    all = "الكل",
    send = "إرسال",
    apply = "تطبيق",
    accept = "قبول",
    reject = "رفض",
    delete = "حذف",
    fillAllFields = "أكمل جميع الحقول",
    noConnection = "لا يوجد اتصال بالخادم",
    layoutDirection = LayoutDirection.Rtl,
    undoWarning = "لا يمكن التراجع عن هذا الإجراء.",
    goBack = "رجوع",

    navHome = "الرئيسية",
    navCitas = "المواعيد",
    navVehiculos = "المركبات",
    navReparaciones = "الإصلاحات",
    navPerfil = "الملف الشخصي",

    appSubtitle = "إدارة ورش السيارات",
    emailField = "البريد الإلكتروني",
    passwordField = "كلمة المرور",
    showPassword = "إظهار",
    hidePassword = "إخفاء",
    loginButton = "تسجيل الدخول",
    noAccount = "ليس لديك حساب؟",
    registerLink = "سجّل الآن",
    registerTitle = "انضم إلى AutoElite",
    registerSubtitle = "أنشئ حسابك لإدارة مواعيدك ومركباتك",
    firstNameField = "الاسم",
    lastNameField = "الكنية",
    confirmPasswordField = "تأكيد كلمة المرور",
    passwordsNotMatch = "كلمات المرور غير متطابقة",
    minPasswordChars = "٦ أحرف على الأقل",
    createAccountButton = "إنشاء حساب",
    alreadyHaveAccount = "لديك حساب بالفعل؟",
    signInLink = "تسجيل الدخول",

    homeGreeting = { "مرحباً، $it" },
    homeSubtitle = "أهلاً بك في ورشتك الموثوقة",
    quickAccess = "الوصول السريع",
    quickCitas = "حجز موعد",
    quickCitasSub = "حدد زيارتك",
    quickReparaciones = "الإصلاحات",
    quickReparacionesSub = "تتبع مباشر",
    quickVehiculos = "المركبات",
    quickVehiculosSub = "إدارة مركباتك",
    quickCrm = "نقاط CRM",
    quickCrmSub = "استبدل المكافآت",
    quickFacturas = "الفواتير",
    quickFacturasSub = "ادفع عبر الإنترنت",
    quickHistorial = "السجل",
    quickHistorialSub = "نشاطك",
    nextCita = "الموعد القادم",
    serviceLabel = "خدمة",
    noCitasScheduled = "لا توجد مواعيد مجدولة",
    bookNextCita = "احجز موعدك القادم الآن",
    notificationsLabel = "الإشعارات",

    myCitas = "مواعيدي",
    searchCitasHint = "البحث بالمركبة أو النوع أو التاريخ…",
    noCitas = "لا توجد مواعيد بعد",
    noCitasFilter = "لم يتم العثور على مواعيد بهذه المرشحات",
    bookCita = "حجز موعد",
    newCita = "موعد جديد",
    cancelCitaTitle = "إلغاء الموعد",
    cancelCitaQuestion = { date, time -> "هل أنت متأكد من إلغاء الموعد في $date الساعة $time؟" },
    vehicleField = "المركبة",
    dateField = "التاريخ",
    availableSlots = "الأوقات المتاحة:",
    noSlotsAvailable = "لا توجد أوقات متاحة لهذا اليوم.",
    selectDateFirst = "اختر تاريخاً لرؤية الأوقات المتاحة",
    serviceTypeField = "نوع الخدمة",
    workshopConfirmDesc = "ستؤكد الورشة التوافر",
    requestButton = "طلب",
    citaCountLabel = { n -> "$n موعد" },
    filterAll = "الكل",
    filterPending = "معلقة",
    filterConfirmed = "مؤكدة",
    filterCancelled = "ملغاة",
    noVehiclesForCita = "لا توجد مركبات مسجلة",
    citaStatusPending = "PENDIENTE",
    citaStatusConfirmed = "CONFIRMADA",
    citaStatusCancelled = "CANCELADA",

    myVehiculos = "مركباتي",
    noVehiculos = "لا توجد مركبات مسجلة",
    addVehiculo = "إضافة مركبة",
    updateKmButton = "تحديث العداد",
    deleteVehiculoButton = "حذف",
    deleteVehiculoTitle = "حذف المركبة",
    deleteVehiculoText = { m, mo, p -> "هل أنت متأكد من حذف $m $mo ($p)؟\n\nلا يمكن التراجع عن هذا الإجراء." },
    brandField = "الماركة",
    modelField = "الموديل",
    yearField = "السنة",
    plateField = "رقم اللوحة",
    mileageField = "عداد المسافة",
    currentMileageLabel = { km -> "العداد الحالي: $km كم" },
    newMileageField = "العداد الجديد",
    vehiculoAddedMsg = "تمت إضافة المركبة",
    vehiculoDeletedMsg = "تم حذف المركبة",
    kmUpdatedMsg = "تم تحديث العداد",
    invalidNumberError = "أدخل رقماً صحيحاً",
    negativeKmError = "لا يمكن أن يكون العداد سالباً",
    kmCannotDecreaseError = { km -> "لا يمكن أن يكون أقل من الحالي ($km كم)" },
    cannotDeleteVehiculo = "لا يمكن الحذف: توجد مواعيد أو إصلاحات مرتبطة",
    updateMileageTitle = "تحديث عداد المسافة",
    kmSuffix = "كم",

    myReparaciones = "إصلاحاتي",
    searchReparacionesHint = "البحث بالمركبة أو اللوحة أو الميكانيكي…",
    noReparaciones = "لا توجد إصلاحات نشطة",
    noReparacionesFilter = "لم يتم العثور على إصلاحات",
    mechanicLabel = "الميكانيكي:",
    costLabel = "التكلفة:",
    vehicleStatusLabel = "حالة المركبة",
    rejectedRepairLabel = "تم رفض الإصلاح",
    repairPresentedDesc = "قدّمت الورشة هذا الإصلاح. هل تريد قبوله؟",
    rateRepairButton = "تقييم الإصلاح",
    ratingSentMsg = "تم إرسال التقييم. شكراً!",
    acceptRepairTitle = "قبول الإصلاح",
    rejectRepairTitle = "رفض الإصلاح",
    acceptRepairText = { v, p, c -> "هل تقبل إصلاح $v · $p بتكلفة $c €؟\n\nستبدأ الورشة العمل على مركبتك." },
    rejectRepairText = { v, p -> "هل أنت متأكد من رفض إصلاح $v · $p؟\n\nلا يمكن التراجع عن هذا الإجراء." },
    howWasExperience = "كيف كانت تجربتك؟",
    commentOptional = "تعليق (اختياري)",
    stepPresented = "مقدَّم",
    stepInProgress = "قيد التنفيذ",
    stepFinished = "منتهي",
    stepConfirmed = "مؤكد",
    ratingVeryBad = "سيء جداً",
    ratingBad = "سيء",
    ratingNormal = "عادي",
    ratingGood = "جيد",
    ratingExcellent = "ممتاز",
    reparacionCountLabel = { n -> "$n إصلاح" },
    filterPresented = "مقدَّمة",
    filterInProgress = "قيد التنفيذ",
    filterFinished = "منتهية",
    filterConfirmedRep = "مؤكدة",
    filterRejected = "مرفوضة",
    ratingRepair = "تقييم الإصلاح",

    myFacturas = "فواتيري",
    searchFacturasHint = "البحث برقم الفاتورة أو التاريخ أو المبلغ…",
    noFacturas = "لا توجد فواتير بعد",
    noFacturasFilter = "لم يتم العثور على فواتير",
    paidLabel = "✓ مدفوعة",
    unpaidLabel = "غير مدفوعة",
    paymentMethodLabel = "طريقة الدفع:",
    sharePdfButton = "مشاركة PDF",
    payButton = "دفع",
    generatingLabel = "جار الإنشاء…",
    payingLabel = "جار الدفع…",
    pdfErrorMsg = "خطأ في إنشاء PDF",
    facturaCountLabel = { n -> "$n فاتورة" },
    filterAllFacturas = "الكل",
    filterPaidFacturas = "مدفوعة",
    filterUnpaidFacturas = "غير مدفوعة",

    myPointsTitle = "نقاطي",
    ptsLabel = "نقطة",
    levelLabel = "المستوى:",
    goldLevel = "ذهبي 🥇",
    silverLevel = "فضي 🥈",
    bronzeLevel = "برونزي 🥉",
    maxLevelReached = "لقد وصلت إلى المستوى الأعلى",
    pointsToGold = { pts -> "الذهبي — تحتاج $pts نقطة" },
    pointsToSilver = { pts -> "الفضي — تحتاج $pts نقطة" },
    availableRewards = "المكافآت المتاحة",
    pointsInfoText = "تجمع النقاط مع كل إصلاح. ١ يورو = ١ نقطة.",
    redeemButton = "استبدال",
    redeemingLabel = "جار الاستبدال…",
    redeemRewardTitle = "استبدال مكافأة",
    confirmRedeemButton = "تأكيد الاستبدال",
    yourCurrentPoints = "نقاطك الحالية:",
    rewardCostLabel = "تكلفة المكافأة:",
    remainingPointsLabel = "النقاط المتبقية:",
    redeemEmailInfo = "ستصلك رسالة بالبريد الإلكتروني للاستخدام في زيارتك القادمة.",
    reward1Title = "خصم ١٠٪",
    reward1Desc = "على إصلاحك القادم",
    reward2Title = "فحص مجاني",
    reward2Desc = "فحص شامل بدون تكلفة",
    reward3Title = "تغيير الزيت",
    reward3Desc = "شامل أجور العمالة",
    reward4Title = "خصم ٢٥٪",
    reward4Desc = "على أي خدمة",

    notificationsTitle = "الإشعارات",
    markAllRead = "تحديد الكل كمقروء",
    noNotifications = "لا توجد إشعارات",
    noNotificationsDesc = "ستظهر هنا تحديثات مواعيدك\nوإصلاحاتك وفواتيرك",

    historialTitle = "السجل",
    noHistory = "لا يوجد نشاط بعد",
    noHistoryDesc = "ستظهر هنا مواعيدك وإصلاحاتك ومدفوعاتك",
    citasHistLabel = "المواعيد",
    reparacionesHistLabel = "الإصلاحات",
    facturasHistLabel = "الفواتير",
    appointmentServiceLabel = "موعد خدمة",
    mechanicHistLabel = { mec -> "الميكانيكي: $mec" },
    paidHistLabel = "مدفوعة",
    unpaidHistLabel = "في انتظار الدفع",
    monthNames = listOf("يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"),
    statusReadable = { e -> when(e) { "PENDIENTE"->"معلق"; "CONFIRMADA"->"مؤكد"; "CANCELADA"->"ملغى"; "EN_PROCESO"->"قيد التنفيذ"; "TERMINADA"->"منتهي"; "PRESENTADA"->"مقدَّم"; else->e } },

    myProfile = "ملفي الشخصي",
    pointsAccumulated = { pts -> "$pts نقطة مجمّعة" },
    appearanceSection = "المظهر",
    darkModeLabel = "الوضع الداكن",
    languageLabel = "اللغة",
    languageDialogTitle = "لغة التطبيق",
    languageDialogDesc = "سيتكيف التطبيق مع اللغة المختارة تلقائياً.",
    accountSection = "الحساب",
    editPersonalDataLabel = "تعديل البيانات الشخصية",
    changePasswordLabel = "تغيير كلمة المرور",
    notifSectionLabel = "الإشعارات",
    supportSection = "الدعم",
    workshopLocationLabel = "موقع الورشة",
    contactWorkshopLabel = "التواصل مع الورشة",
    aboutAutoEliteLabel = "حول AutoElite",
    logoutButton = "تسجيل الخروج",
    logoutTitle = "تسجيل الخروج؟",
    logoutDesc = "سيتم إغلاق جلستك على هذا الجهاز.",
    exitButton = "خروج",
    editDataTitle = "تعديل البيانات",
    nameField = "الاسم",
    surnamesField = "الكنية",
    phoneField = "الهاتف",
    currentPasswordFieldLabel = "كلمة المرور الحالية",
    newPasswordFieldLabel = "كلمة المرور الجديدة",
    confirmNewPasswordField = "تأكيد الجديدة",
    changePasswordButton = "تغيير",
    citasNotifLabel = "المواعيد والتذكيرات",
    repairsNotifLabel = "حالة الإصلاحات",
    promoNotifLabel = "العروض والترقيات",
    savedAutomatically = "يتم الحفظ تلقائياً",
    openInMaps = "فتح في الخرائط",
    callButton = { tel -> "اتصال: $tel" },
    emailButton = { mail -> "بريد: $mail" },
    whatsappButton = "واتساب",
    versionLabel = "الإصدار",
    developerLabel = "المطوّر",
    platformLabel = "المنصة",
    backendLabel = "الخادم",
    aboutDescText = "تطبيق تم تطويره كمشروع تخرج لإدارة المواعيد والمركبات والإصلاحات والفوترة.",
    spanishLang = "Español",
    englishLang = "English",
    arabicLang = "العربية",
    workshopNameLabel = "ورشة AutoElite",
    workshopAddressLabel = "شارع المثال ٤٢، مدريد 28001",
    workshopSchedule = "الاثنين–الجمعة: ٨:٠٠–١٨:٠٠\nالسبت: ٩:٠٠–١٤:٠٠",
    changePasswordTitle = "تغيير كلمة المرور",
    errorGeneric = "حدث خطأ",
)

// CompositionLoca
val LocalAppStrings = compositionLocalOf<AppStrings> { StringsEs }

fun getStrings(language: String): AppStrings = when (language) {
    "en" -> StringsEn
    "ar" -> StringsAr
    else -> StringsEs
}